include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - build/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
